version: '3'
services:
    db: 
        image: postgres:latest
        environment: 
            - POSTGRES_PASSWORD=p@ssw0rd42
        restart: always
        volumes:
            - ./database:/var/lib/postgresql/data
        ports:
            - "5432:5432"