# create location
POST http://localhost:9999/locations
Content-Type: application/json

{
    "name": "melbourne",
    "description": "Melourne DC"
}

###
# Get all locations
GET http://localhost:9999/locations

###
# Get location by id 
GET http://localhost:9999/locations/1



