# create location
POST http://localhost:9999/locations
Content-Type: application/json

{
    "name": "sydney",
    "description": "Sydney DC"
}

###
# Get all locations
GET http://localhost:9999/locations

###
# Get location by id 
GET http://localhost:9999/locations/2

###
# Create server
POST http://localhost:9999/servers
Content-Type: application/json

{
    "ip": "testIP",
    "hostname": "testhostname",
    "location": {
        "name": "testLocation"
    }
}



